As an admin, I want to be able to see / change images in back-office
IncSow/mono_repo_b3_g2 pull request #142
Opened 2023-06-29 09:33 UTC by amorfus78

See / Change images in product / images

2023-06-29 17:31 UTC, DenisMarine requested changes

2023-06-29 17:31 UTC, DenisMarine commented on back-end-g2/src/routes/products/productImagesRoutes.js
> +            product_id: productId,
I let you see the patch of categoryProductsRoutes. It allows to make fewer calls to the database

2023-06-29 17:31 UTC, DenisMarine commented on front-end/src/pages/back-office/images/update/[imageId].jsx
> +      if (error) {
use getServerSideProps to make get and not useEffect ! And not
getImage(imageId).then([error, data] ...)
but
const [error, data] = await getImage(imageId)

2023-06-29 19:54 UTC, amorfus78 commented on back-end-g2/src/middleware/uploadImageToS3.js
> +    return [Error("Invalid file"), null]
to let the client know if there was an issue with the upload

2023-06-29 19:55 UTC, amorfus78 commented on back-end-g2/src/routes/imagesRoutes.js
>            canSendResult = false
if we already had an error on the first image, we would resend another error to the client, which would lead to a crash

2023-06-29 19:57 UTC, amorfus78 commented on back-end-g2/src/routes/imagesRoutes.js
> +          canSendResult = false
same as above. 
Thinking about it, we could just prevent (test) at the start of the loop.

2023-06-30 12:43 UTC, amorfus78 commented on back-end-g2/src/routes/products/productImagesRoutes.js
> +            product_id: productId,
Donen, I've follwed the same philosophy as `productImagesRoutes$

2023-06-30 12:43 UTC, amorfus78 commented on front-end/src/pages/back-office/images/update/[imageId].jsx
> +      if (error) {
done for this file (all the others in next pr)

2023-06-30 13:48 UTC, merged